language: node_js
node_js:
  - 0.8  # previous stable release
  - 0.10 # latest stable release
  - 0.11 # latest development release

# This causes `Job is already running: mysql`
#services:
#  - mysql # start MySQL on startup

before_install:
  - sudo apt-get update
  - sudo apt-get install libmysqlclient-dev
  - sudo apt-get install php5-cli php5-mysql
before_script:
  - "mysql -uroot -e \"DELETE FROM mysql.db WHERE Db = 'test';\""
  - "mysql -uroot -e \"DELETE FROM mysql.user WHERE Host = 'localhost' AND User = '';\""
  - "mysql -uroot -e \"FLUSH PRIVILEGES;\""
  - "mysql -uroot -e \"CREATE DATABASE IF NOT EXISTS test DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;\""
  - "mysql -uroot -e \"GRANT ALL PRIVILEGES ON test.* TO 'test'@'localhost' IDENTIFIED BY '';\""
  - "mysql -uroot -e \"FLUSH PRIVILEGES;\""
  # Some extras for Travis-CI only
  - "mysql -uroot -e \"DELETE FROM mysql.user WHERE User = 'travis';\""
  - "mysql -uroot -e \"FLUSH PRIVILEGES;\""
script:
  - make benchmark
